[manifest]
group-filter = ["-babblesim", "-optional"]

[[manifest.projects]]
name = "zephyr"
url = "https://github.com/zephyrproject-rtos/zephyr"
revision = "3568e1b6d5cdd51a6b964a2a1d6d29200fea2056"
clone-depth = 1
west-commands = "scripts/west-commands.yml"

[manifest.projects.nix]
hash = "sha256-45b6RenIwudBfZHvNBSdAg4QV5muZ8EPAqjPbViclHA="

[[manifest.projects]]
name = "cmsis"
url = "https://github.com/zephyrproject-rtos/cmsis"
revision = "512cc7e895e8491696b61f7ba8066b4a182569b8"
path = "modules/hal/cmsis"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-vzCbE69wCMLIjrSz1m8yspgVCto4JSm4Qg5zY/Ozg+k="

[[manifest.projects]]
name = "hal_nordic"
url = "https://github.com/zephyrproject-rtos/hal_nordic"
revision = "7858281d843468fe53c829995fb63f45a227387a"
path = "modules/hal/nordic"
groups = ["hal"]

[manifest.projects.nix]
hash = "sha256-VJNN0xuGHX1s1VnBRraay5GuQo/7gBxJWFsZdQFxNQM="

[manifest.self]
path = "app"
