/**
 * @file generated_struct_SpiBuffer.h
 *
 * @brief A SPI buffer containing a chip select and transeive data
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-19
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef GENERATED_STRUCT_SPI_BUFFER_H
#define GENERATED_STRUCT_SPI_BUFFER_H

#include <stdint.h>

#include "buffer.h"
#include "datastore_types.h"

/**
 * @addtogroup datastore
 * @{
 */

//**********************************************************
//* Definitions
//**********************************************************

#define SPI_BUFFER_BYTES_MIN_LEN 0    /**< Minimum length of Bytes */
#define SPI_BUFFER_BYTES_MAX_LEN 6    /**< Maximum length of Bytes */
#define SPI_BUFFER_TEXT_MIN_LEN 3     /**< Minimum length of Text */
#define SPI_BUFFER_TEXT_MAX_LEN 12    /**< Maximum length of Text */
#define SPI_BUFFER_BUFFER_MIN_LEN 0   /**< Minimum length of Buffer */
#define SPI_BUFFER_BUFFER_MAX_LEN 512 /**< Maximum length of Buffer */

//**********************************************************
//* Typedefs, Enums, and Structs
//**********************************************************

/**
 * @brief A SPI buffer containing a chip select and transeive data
 */
typedef struct
{
    int cs;                                                     /**< CS field */
    uint8_t bytes[sizeof(buffer_t) + SPI_BUFFER_BYTES_MAX_LEN]; /**< Bytes field */
    char text[SPI_BUFFER_TEXT_MAX_LEN + 1];                     /**< Text field */
    buffer_t* buffer;                                           /**< Buffer field */
} SpiBuffer_t;

/**
 * @brief Datastore interface for SpiBuffer struct type
 */
extern const struct datastore_item_interface datastore_struct_spi_buffer_interface;

/**
 * @}
 */

#endif  // GENERATED_STRUCT_SPI_BUFFER_H
