/**
 * @file generated_datastore_items.h
 *
 * @brief Datastore item definitions
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @author Demizo (demizodemazo@gmail.com)
 * @version 0.1
 * @date 2026-03-01
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef GENERATED_DATASTORE_ITEMS_H
#define GENERATED_DATASTORE_ITEMS_H

#include <stddef.h>
#include <stdint.h>
#include <zephyr/kernel.h>

#include "buffer.h"
#include "datastore_types.h"

/**
 * @addtogroup datastore
 * @{
 */

//**********************************************************
//* Definitions
//**********************************************************

#define DATASTORE_HASH_MIN_LEN 0
#define DATASTORE_HASH_MAX_LEN 16
#define DEVICE_NAME_MIN_LEN 1
#define DEVICE_NAME_MAX_LEN 25
#define VERSION_CODE_MIN 0
#define VERSION_CODE_MAX INT_MAX
#define TEST_FLOAT_MIN 0.0f
#define TEST_FLOAT_MAX 32.0f
#define TEST_BYTES_MIN_LEN 6
#define TEST_BYTES_MAX_LEN 6
#define TEST_BUFFER_MIN_LEN 0
#define TEST_BUFFER_MAX_LEN 20

//**********************************************************
//* Typedefs, Enums, and Structs
//**********************************************************

/**
 * @brief ID for each datastore item
 *
 * @details The numeric ID is static for each firmware version, however IDs may
 * change between firmware versions. The name of each data item is its unique
 * key, not the ID.
 */
enum datastore_item_id
{
    DATASTORE_ID_DATASTORE_HASH,
    DATASTORE_ID_DEVICE_NAME,
    DATASTORE_ID_VERSION_CODE,
    DATASTORE_ID_TEST_FLOAT,
    DATASTORE_ID_TEST_BYTES,
    DATASTORE_ID_TEST_BUFFER,
    DATASTORE_ID_COUNT
};

/**
 * @brief Structure containing all item values
 */
struct datastore_values
{
    char datastore_hash[DATASTORE_HASH_MAX_LEN + 1];           /**< Hash of the datastore */
    char device_name[DEVICE_NAME_MAX_LEN + 1];                 /**< Device name */
    int version_code;                                          /**< Version code */
    float test_float;                                          /**< Test float */
    uint8_t test_bytes[sizeof(buffer_t) + TEST_BYTES_MAX_LEN]; /**< Test bytes */
    buffer_t* test_buffer;                                     /**< Test buffer */
};

/**
 * @brief Global datastore definition containing the constant metadata for each data item
 */
extern const struct datastore_item_const_metadata g_datastore_const_metadata[DATASTORE_ID_COUNT];

//**********************************************************
//* Functions
//**********************************************************

/**
 * @}
 */

#endif  // GENERATED_DATASTORE_ITEMS_H
