/**
 * @file generated_datastore_enums.h
 *
 * @brief Datastore enumeration declarations
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-18
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef GENERATED_DATASTORE_ENUMS_H
#define GENERATED_DATASTORE_ENUMS_H

#include "datastore_types.h"

/**
 * @addtogroup datastore
 * @{
 */

/**
 * @brief Bluetooth Connection State
 */
enum BleConnectionState
{
    BleConnectionState_DISCONNECTED = 0,
    BleConnectionState_CONNECTED = 1,
};

/**
 * @brief Values for BleConnectionState
 */
extern const struct data_enum_value BleConnectionState_enum_values[2];

/**
 * @brief A toggle to enable or disable
 */
enum Toggle
{
    Toggle_DISABLED = 0,
    Toggle_ENABLED = 1,
};

/**
 * @brief Values for Toggle
 */
extern const struct data_enum_value Toggle_enum_values[2];

/**
 * @brief A SPI chip select index
 */
enum SpiChipSelect
{
    SpiChipSelect_SPI_CS0 = 0,
    SpiChipSelect_SPI_CS1 = 1,
};

/**
 * @brief Values for SpiChipSelect
 */
extern const struct data_enum_value SpiChipSelect_enum_values[2];

/**
 * @}
 */

#endif  // GENERATED_DATASTORE_ENUMS_H
