/**
 * @file generated_datastore_items.h
 *
 * @brief Datastore item definitions
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @author Demizo (demizodemazo@gmail.com)
 * @version 0.1
 * @date 2026-03-01
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef GENERATED_DATASTORE_ITEMS_H
#define GENERATED_DATASTORE_ITEMS_H

#include <stddef.h>
#include <zephyr/kernel.h>

#include "datastore_types.h"

/**
 * @addtogroup datastore
 * @{
 */

//**********************************************************
//* Definitions
//**********************************************************

//**********************************************************
//* Typedefs, Enums, and Structs
//**********************************************************

/**
 * @brief ID for each datastore item
 *
 * @details The numeric ID is static for each firmware version, however IDs may
 * change between firmware versions. The name of each data item is its unique
 * key, not the ID.
 */
enum datastore_item_id
{
    DATASTORE_ID_DATASTORE_HASH,
    DATASTORE_ID_DEVICE_NAME,
    DATASTORE_ID_VERSION_CODE,
    DATASTORE_ID_COUNT
};

/**
 * @brief Structure containing all item values
 */
struct datastore_values
{
    char datastore_hash[32]; /**< Hash of the datastore */
    char device_name[32];    /**< Device name */
    int version_code;        /**< Version code */
};

/**
 * @brief Global datastore definition containing the constant metadata for each data item
 */
extern const struct datastore_item_const_metadata g_datastore_const_metadata[DATASTORE_ID_COUNT];

//**********************************************************
//* Functions
//**********************************************************

/**
 * @}
 */

#endif  // GENERATED_DATASTORE_ITEMS_H
