/**
 * @file generated_datastore_items.h
 *
 * @brief Datastore item definitions
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-18
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef GENERATED_DATASTORE_ITEMS_H
#define GENERATED_DATASTORE_ITEMS_H

#include <stddef.h>
#include <stdint.h>
#include <zephyr/kernel.h>

#include "buffer.h"
#include "datastore_types.h"
#include "generated_datastore_enums.h"
#include "generated_struct_SpiBuffer.h"

/**
 * @addtogroup datastore
 * @{
 */

//**********************************************************
//* Definitions
//**********************************************************

#define DEVICE_NAME_MIN_LEN 3       /**< Minimum length of DeviceName */
#define DEVICE_NAME_MAX_LEN 25      /**< Maximum length of DeviceName */
#define SERIAL_NUMBER_MIN_LEN 16    /**< Minimum length of SerialNumber */
#define SERIAL_NUMBER_MAX_LEN 16    /**< Maximum length of SerialNumber */
#define FIRMWARE_VERSION_MIN_LEN 6  /**< Minimum length of FirmwareVersion */
#define FIRMWARE_VERSION_MAX_LEN 32 /**< Maximum length of FirmwareVersion */
#define TEST_INT_MIN -100           /**< Minimum value of TestInt */
#define TEST_INT_MAX 100            /**< Maximum value of TestInt */
#define TEST_FLOAT_MIN 15.0f        /**< Minimum value of TestFloat */
#define TEST_FLOAT_MAX 30.0f        /**< Maximum value of TestFloat */
#define TEST_BYTES_MIN_LEN 12       /**< Minimum length of TestBytes */
#define TEST_BYTES_MAX_LEN 12       /**< Maximum length of TestBytes */
#define TEST_BUFFER_MIN_LEN 0       /**< Minimum length of TestBuffer */
#define TEST_BUFFER_MAX_LEN 20      /**< Maximum length of TestBuffer */

//**********************************************************
//* Typedefs, Enums, and Structs
//**********************************************************

/**
 * @brief ID for each datastore item
 *
 * @details The numeric ID is static for each firmware version, however IDs may
 * change between firmware versions. The name of each data item is its unique
 * key, not the ID.
 */
enum datastore_item_id
{
    DATASTORE_ID_DEVICE_NAME,          /**< The name of the device */
    DATASTORE_ID_SERIAL_NUMBER,        /**< The device serial number */
    DATASTORE_ID_FIRMWARE_VERSION,     /**< The current firmware version */
    DATASTORE_ID_BLE_CONNECTION_STATE, /**< The current BLE connection state */
    DATASTORE_ID_TEST_ENUM,            /**< Test enum value */
    DATASTORE_ID_TEST_INT,             /**< Test int value */
    DATASTORE_ID_TEST_FLOAT,           /**< Test float value */
    DATASTORE_ID_TEST_BYTES,           /**< Test bytes */
    DATASTORE_ID_TEST_BUFFER,          /**< Test buffer */
    DATASTORE_ID_SPI_TX_BUFFER,        /**< SPI TX buffer */
    DATASTORE_ID_COUNT
};

/**
 * @brief Structure containing all item values
 */
struct datastore_values
{
    char device_name[DEVICE_NAME_MAX_LEN + 1];                 /**< The name of the device */
    char serial_number[SERIAL_NUMBER_MAX_LEN + 1];             /**< The device serial number */
    char firmware_version[FIRMWARE_VERSION_MAX_LEN + 1];       /**< The current firmware version */
    int ble_connection_state;                                  /**< The current BLE connection state */
    int test_enum;                                             /**< Test enum value */
    int test_int;                                              /**< Test int value */
    float test_float;                                          /**< Test float value */
    uint8_t test_bytes[sizeof(buffer_t) + TEST_BYTES_MAX_LEN]; /**< Test bytes */
    buffer_t* test_buffer;                                     /**< Test buffer */
    SpiBuffer_t* spi_tx_buffer;                                /**< SPI TX buffer */
};

/**
 * @brief Global datastore definition containing the constant metadata for each data item
 */
extern const struct datastore_item_const_metadata g_datastore_const_metadata[DATASTORE_ID_COUNT];

/**
 * @}
 */

#endif  // GENERATED_DATASTORE_ITEMS_H
