/**
 * @file generated_struct_SpiBuffer.h
 *
 * @brief A SPI buffer containing a chip select and transeive data
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-19
 *
 * @copyright Copyright (c) 2026
 *
 */

#ifndef GENERATED_STRUCT_SPI_BUFFER_H
#define GENERATED_STRUCT_SPI_BUFFER_H

#include <stdint.h>

#include "buffer.h"
#include "datastore_types.h"

/**
 * @addtogroup datastore
 * @{
 */

/**
 * @brief A SPI buffer containing a chip select and transeive data
 */
typedef struct
{
    int cs;                              /**< CS field */
    uint8_t bytes[sizeof(buffer_t) + 6]; /**< Bytes field */
    char text[12 + 1];                   /**< Text field */
    buffer_t* buffer;                    /**< Buffer field */
} SpiBuffer_t;

/**
 * @brief Datastore interface for SpiBuffer struct type
 */
extern const struct datastore_item_interface datastore_struct_spi_buffer_interface;

/**
 * @}
 */

#endif  // GENERATED_STRUCT_SPI_BUFFER_H
