/**
 * @file generated_struct_SpiBuffer.c
 *
 * @brief Datastore interface implementation for SpiBuffer struct type
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-19
 *
 * @copyright Copyright (c) 2026
 *
 */

#include "generated_struct_SpiBuffer.h"

#include <stdint.h>
#include <string.h>
#include <sys/errno.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>

#include "buffer.h"
#include "datastore_type_buffer.h"
#include "datastore_type_byte_array.h"
#include "datastore_type_enum.h"
#include "datastore_type_float.h"
#include "datastore_type_int.h"
#include "datastore_type_string.h"
#include "datastore_types.h"
#include "error.h"
#include "generated_datastore_enums.h"
#include "memory.h"

/**
 * @brief Logger for module
 */
LOG_MODULE_REGISTER(datastore_struct_spi_buffer, CONFIG_DATASTORE_TYPES_LOG_LEVEL);

//**********************************************************
//* Static Function Declarations
//**********************************************************

static bool validate(const union datastore_constraints* constraints, data_value_t value);
static bool is_equal(data_value_t a, data_value_t b);
static void set(void* dest, data_value_t value);
static int get(const struct datastore_item_const_metadata* item, data_value_t* out_value);
static void release(data_value_t* value);
static int encode(zcbor_state_t* encoder, data_value_t value);
static int decode(zcbor_state_t* decoder, data_value_t* out_value);
static int encode_constraints(zcbor_state_t* encoder, const union datastore_constraints* constraints);

//**********************************************************
//* Static Variable Definitions
//**********************************************************

static const union datastore_constraints cs_constraints = {
    .enum_constraints = {
        .value_count = 2,
        .values = SpiChipSelect_enum_values,
    },
};

static const union datastore_constraints bytes_constraints = {
    .buffer_constraints = {
        .min_len = 0,
        .max_len = 6,
    },
};

static const union datastore_constraints text_constraints = {
    .buffer_constraints = {
        .min_len = 3,
        .max_len = 12,
    },
};

static const union datastore_constraints buffer_constraints = {
    .buffer_constraints = {
        .min_len = 0,
        .max_len = 512,
    },
};

//**********************************************************
//* Static Function Definitions
//**********************************************************

static bool validate(const union datastore_constraints* constraints, data_value_t value)
{
    ARG_UNUSED(constraints);
    ASSERT(value.type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");
    SpiBuffer_t* s = (SpiBuffer_t*)value.data.raw_value;

    // Check CS
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_ENUM, .data.int_value = s->cs };
        if (!datastore_enum_interface.validate(&cs_constraints, fval)) return false;
    }
    // Check Bytes
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY, .data.buffer_value = (buffer_t*)s->bytes };
        if (!datastore_byte_array_interface.validate(&bytes_constraints, fval)) return false;
    }
    // Check Text
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_STRING, .data.string_value = s->text };
        if (!datastore_string_interface.validate(&text_constraints, fval)) return false;
    }
    // Check Buffer
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BUFFER, .data.buffer_value = s->buffer };
        if (!datastore_buffer_interface.validate(&buffer_constraints, fval)) return false;
    }

    return true;
}

static bool is_equal(data_value_t a, data_value_t b)
{
    ASSERT((a.type == DATASTORE_ITEM_TYPE_STRUCT) && (b.type == DATASTORE_ITEM_TYPE_STRUCT), "Unexpected value type");
    SpiBuffer_t* a_struct = (SpiBuffer_t*)a.data.raw_value;
    SpiBuffer_t* b_struct = (SpiBuffer_t*)b.data.raw_value;

    data_value_t a_value = { 0 };
    data_value_t b_value = { 0 };
    // Check CS
    a_value.type = DATASTORE_ITEM_TYPE_ENUM;
    a_value.data.int_value = a_struct->cs;
    b_value.type = DATASTORE_ITEM_TYPE_ENUM;
    b_value.data.int_value = b_struct->cs;
    if (!datastore_enum_interface.is_equal(a_value, b_value)) return false;
    // Check Bytes
    a_value.type = DATASTORE_ITEM_TYPE_BYTE_ARRAY;
    a_value.data.buffer_value = (buffer_t*)a_struct->bytes;
    b_value.type = DATASTORE_ITEM_TYPE_BYTE_ARRAY;
    b_value.data.buffer_value = (buffer_t*)b_struct->bytes;
    if (!datastore_byte_array_interface.is_equal(a_value, b_value)) return false;
    // Check Text
    a_value.type = DATASTORE_ITEM_TYPE_STRING;
    a_value.data.string_value = a_struct->text;
    b_value.type = DATASTORE_ITEM_TYPE_STRING;
    b_value.data.string_value = b_struct->text;
    if (!datastore_string_interface.is_equal(a_value, b_value)) return false;
    // Check Buffer
    a_value.type = DATASTORE_ITEM_TYPE_BUFFER;
    a_value.data.buffer_value = a_struct->buffer;
    b_value.type = DATASTORE_ITEM_TYPE_BUFFER;
    b_value.data.buffer_value = b_struct->buffer;
    if (!datastore_buffer_interface.is_equal(a_value, b_value)) return false;

    return true;
}

static void release_struct_fields(SpiBuffer_t* s)
{
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_STRING, .data.string_value = s->text };
        datastore_string_interface.release(&fval);
    }
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BUFFER, .data.buffer_value = s->buffer };
        datastore_buffer_interface.release(&fval);
    }
    (void)s;
}

static void set(void* dest, data_value_t value)
{
    ASSERT(value.type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");
    SpiBuffer_t* src = (SpiBuffer_t*)value.data.raw_value;

    // Allocate new struct block
    void* new_block = NULL;
    int ret = mem_alloc(sizeof(SpiBuffer_t), &new_block);
    if (ret != SUCCESS)
    {
        PASS_OWNERSHIP(new_block);
        return;
    }

    SpiBuffer_t* new_struct = (SpiBuffer_t*)new_block;
    memset(new_struct, 0, sizeof(SpiBuffer_t));

    // Copy CS
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_ENUM, .data.int_value = src->cs };
        datastore_enum_interface.set(&(new_struct->cs), fval);
    }

    // Copy Bytes
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY, .data.buffer_value = (buffer_t*)src->bytes };
        datastore_byte_array_interface.set(&(new_struct->bytes), fval);
    }

    // Copy Text
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_STRING, .data.string_value = src->text };
        datastore_string_interface.set(&(new_struct->text), fval);
    }

    // Copy Buffer
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BUFFER, .data.buffer_value = src->buffer };
        datastore_buffer_interface.set(&(new_struct->buffer), fval);
    }

    // Release old value
    SpiBuffer_t* old_struct = *(SpiBuffer_t**)dest;
    if (old_struct != NULL)
    {
        data_value_t old_value = { .type = DATASTORE_ITEM_TYPE_STRUCT, .data.raw_value = old_struct };
        release(&old_value);
    }

    *(SpiBuffer_t**)dest = (SpiBuffer_t*)new_block;
    PASS_OWNERSHIP(new_block);
}

static int get(const struct datastore_item_const_metadata* item, data_value_t* out_value)
{
    SpiBuffer_t* current = *(SpiBuffer_t**)item->value_ptr;

    mem_ref(current);
    out_value->type = DATASTORE_ITEM_TYPE_STRUCT;
    out_value->data.raw_value = current;

    PASS_OWNERSHIP(current);
    return SUCCESS;
}

static void release(data_value_t* value)
{
    ASSERT(value->type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");

    SpiBuffer_t* s = (SpiBuffer_t*)value->data.raw_value;

    // Free fields if struct is about to be freed
    if (s != NULL && mem_get_ref_count((void*)s) == 1)
    {
        release_struct_fields(s);
    }

    void* ptr = s;
    mem_unref(&ptr);
}

static int encode(zcbor_state_t* encoder, data_value_t value)
{
    ASSERT(value.type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");
    SpiBuffer_t* s = (SpiBuffer_t*)value.data.raw_value;

    if (!zcbor_list_start_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    // Encode CS
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_ENUM, .data.int_value = s->cs };
        int ret = datastore_enum_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }
    // Encode Bytes
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY, .data.buffer_value = (buffer_t*)s->bytes };
        int ret = datastore_byte_array_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }
    // Encode Text
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_STRING, .data.string_value = s->text };
        int ret = datastore_string_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }
    // Encode Buffer
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BUFFER, .data.buffer_value = s->buffer };
        int ret = datastore_buffer_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }

    if (!zcbor_list_end_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    return SUCCESS;
}

static int decode(zcbor_state_t* decoder, data_value_t* out_value)
{
    if (!zcbor_list_start_decode(decoder))
    {
        return -EBADMSG;
    }

    void* new_block = NULL;
    int ret = mem_alloc(sizeof(SpiBuffer_t), &new_block);
    if (ret != SUCCESS)
    {
        NOT_REFERENCED(new_block);
        return ret;
    }

    SpiBuffer_t* new_struct = (SpiBuffer_t*)new_block;
    memset(new_struct, 0, sizeof(SpiBuffer_t));

    // Decode CS
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_ENUM;
        ret = datastore_enum_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        datastore_enum_interface.set(&(new_struct->cs), fval);
        datastore_enum_interface.release(&fval);
    }
    // Decode Bytes
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_BYTE_ARRAY;
        ret = datastore_byte_array_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        datastore_byte_array_interface.set(&(new_struct->bytes), fval);
        datastore_byte_array_interface.release(&fval);
    }
    // Decode Text
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_STRING;
        ret = datastore_string_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        datastore_string_interface.set(&(new_struct->text), fval);
        datastore_string_interface.release(&fval);
    }
    // Decode Buffer
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_BUFFER;
        ret = datastore_buffer_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        datastore_buffer_interface.set(&(new_struct->buffer), fval);
        datastore_buffer_interface.release(&fval);
    }

    if (!zcbor_list_end_decode(decoder))
    {
        ret = -EBADMSG;
        goto decode_cleanup;
    }

    out_value->type = DATASTORE_ITEM_TYPE_STRUCT;
    out_value->data.raw_value = new_block;
    PASS_OWNERSHIP(new_block);
    return SUCCESS;

decode_cleanup:
    release_struct_fields(new_struct);
    mem_unref(&new_block);
    return ret;
}

static int encode_constraints(zcbor_state_t* encoder, const union datastore_constraints* constraints)
{
    ARG_UNUSED(constraints);

    if (!zcbor_list_start_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    {
        struct zcbor_string name_str = { .value = "CS", .len = 2 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_ENUM))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_enum_interface.encode_constraints(encoder, &cs_constraints);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }
    {
        struct zcbor_string name_str = { .value = "Bytes", .len = 5 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_BYTE_ARRAY))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_byte_array_interface.encode_constraints(encoder, &bytes_constraints);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }
    {
        struct zcbor_string name_str = { .value = "Text", .len = 4 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_STRING))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_string_interface.encode_constraints(encoder, &text_constraints);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }
    {
        struct zcbor_string name_str = { .value = "Buffer", .len = 6 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_BUFFER))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_buffer_interface.encode_constraints(encoder, &buffer_constraints);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }

    if (!zcbor_list_end_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    return SUCCESS;
}

//**********************************************************
//* Public Function Definitions
//**********************************************************

const struct datastore_item_interface datastore_struct_spi_buffer_interface = {
    .validate = validate,
    .is_equal = is_equal,
    .set = set,
    .get = get,
    .release = release,
    .decode = decode,
    .encode = encode,
    .encode_constraints = encode_constraints,
};
