/**
 * @file generated_datastore_items.c
 *
 * @brief Datastore item definitions
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-24
 *
 * @copyright Copyright (c) 2026
 *
 */

#include "generated_datastore_items.h"

#include <limits.h>

#include "buffer.h"
#include "datastore_type_buffer.h"
#include "datastore_type_byte_array.h"
#include "datastore_type_enum.h"
#include "datastore_type_float.h"
#include "datastore_type_int.h"
#include "datastore_type_string.h"
#include "datastore_types.h"
#include "generated_datastore_enums.h"

//**********************************************************
//* Static Variable Definitions
//**********************************************************

static buffer_t default_test_bytes = {
    .len = 12,
    .buf = { 0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, },
};
static buffer_t default_test_buffer = {
    .len = 0,
};
static buffer_t default_spi_tx_buffer_buffer = {
    .len = 0,
};
static SpiBuffer_t default_spi_tx_buffer = {
    .cs = SpiChipSelect_SPI_CS0,
    .inline_bytes = {
        .len = 3,
        .buf = { 0x01, 0x02, 0x03 },
    },
    .text = "Test",
    .buffer = &default_spi_tx_buffer_buffer,
};

/**
 * @brief The current datastore values
 */
struct datastore_values datastore_values = { 0 };

const struct datastore_item_const_metadata
    g_datastore_const_metadata[DATASTORE_ID_COUNT] = {
        [DATASTORE_ID_DEVICE_NAME] =
        /* The name of the device */
            {
                .id = DATASTORE_ID_DEVICE_NAME,
                .name = "DeviceName",
                .storage_type = DATASTORE_STORAGE_PERSISTENT,
                .permissions = { AUTH_ANY, AUTH_SESSION },
                .type = DATASTORE_ITEM_TYPE_STRING,
                .interface = &datastore_string_interface,
                .value_ptr = &datastore_values.device_name,
                .default_value = { .string_value = "Gantry", },
                .constraints =
                    {
                        .buffer_constraints =
                            {
                                .min_len = DEVICE_NAME_MIN_LEN,
                                .max_len = DEVICE_NAME_MAX_LEN,
                            },
                    },
            },
        [DATASTORE_ID_SERIAL_NUMBER] =
        /* The device serial number */
            {
                .id = DATASTORE_ID_SERIAL_NUMBER,
                .name = "SerialNumber",
                .storage_type = DATASTORE_STORAGE_TOFU,
                .permissions = { AUTH_ANY, AUTH_SESSION },
                .type = DATASTORE_ITEM_TYPE_STRING,
                .interface = &datastore_string_interface,
                .value_ptr = &datastore_values.serial_number,
                .default_value = { .string_value = "0000000000000000", },
                .constraints =
                    {
                        .buffer_constraints =
                            {
                                .min_len = SERIAL_NUMBER_MIN_LEN,
                                .max_len = SERIAL_NUMBER_MAX_LEN,
                            },
                    },
            },
        [DATASTORE_ID_FIRMWARE_VERSION] =
        /* The current firmware version */
            {
                .id = DATASTORE_ID_FIRMWARE_VERSION,
                .name = "FirmwareVersion",
                .storage_type = DATASTORE_STORAGE_PERSISTENT,
                .permissions = { AUTH_ANY, AUTH_NONE },
                .type = DATASTORE_ITEM_TYPE_STRING,
                .interface = &datastore_string_interface,
                .value_ptr = &datastore_values.firmware_version,
                .default_value = { .string_value = "1.0.0", },
                .constraints =
                    {
                        .buffer_constraints =
                            {
                                .min_len = FIRMWARE_VERSION_MIN_LEN,
                                .max_len = FIRMWARE_VERSION_MAX_LEN,
                            },
                    },
            },
        [DATASTORE_ID_BLE_CONNECTION_STATE] =
        /* The current BLE connection state */
            {
                .id = DATASTORE_ID_BLE_CONNECTION_STATE,
                .name = "BleConnectionState",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = { AUTH_ANY, AUTH_INTERNAL },
                .type = DATASTORE_ITEM_TYPE_ENUM,
                .interface = &datastore_enum_interface,
                .value_ptr = &datastore_values.ble_connection_state,
                .default_value = { .int_value = BleConnectionState_DISCONNECTED, },
                .constraints =
                    {
                        .enum_constraints =
                            {
                                .value_count = 2,
                                .values = BleConnectionState_enum_values,
                            },
                    },
            },
        [DATASTORE_ID_TEST_ENUM] =
        /* Test enum value */
            {
                .id = DATASTORE_ID_TEST_ENUM,
                .name = "TestEnum",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = { AUTH_ANY, AUTH_ANY },
                .type = DATASTORE_ITEM_TYPE_ENUM,
                .interface = &datastore_enum_interface,
                .value_ptr = &datastore_values.test_enum,
                .default_value = { .int_value = Toggle_DISABLED, },
                .constraints =
                    {
                        .enum_constraints =
                            {
                                .value_count = 2,
                                .values = Toggle_enum_values,
                            },
                    },
            },
        [DATASTORE_ID_TEST_INT] =
        /* Test int value */
            {
                .id = DATASTORE_ID_TEST_INT,
                .name = "TestInt",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = { AUTH_ANY, AUTH_ANY },
                .type = DATASTORE_ITEM_TYPE_INT,
                .interface = &datastore_int_interface,
                .value_ptr = &datastore_values.test_int,
                .default_value = { .int_value = 0, },
                .constraints =
                    {
                        .int_constraints =
                            {
                                .min = TEST_INT_MIN,
                                .max = TEST_INT_MAX,
                            },
                    },
            },
        [DATASTORE_ID_TEST_FLOAT] =
        /* Test float value */
            {
                .id = DATASTORE_ID_TEST_FLOAT,
                .name = "TestFloat",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = { AUTH_ANY, AUTH_ANY },
                .type = DATASTORE_ITEM_TYPE_FLOAT,
                .interface = &datastore_float_interface,
                .value_ptr = &datastore_values.test_float,
                .default_value = { .float_value = 21.5f, },
                .constraints =
                    {
                        .float_constraints =
                            {
                                .min = TEST_FLOAT_MIN,
                                .max = TEST_FLOAT_MAX,
                            },
                    },
            },
        [DATASTORE_ID_TEST_BYTES] =
        /* Test bytes */
            {
                .id = DATASTORE_ID_TEST_BYTES,
                .name = "TestBytes",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = { AUTH_ANY, AUTH_ANY },
                .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY,
                .interface = &datastore_byte_array_interface,
                .value_ptr = &datastore_values.test_bytes,
                .default_value = { .buffer_value = &default_test_bytes, },
                .constraints =
                    {
                        .buffer_constraints =
                            {
                                .min_len = TEST_BYTES_MIN_LEN,
                                .max_len = TEST_BYTES_MAX_LEN,
                            },
                    },
            },
        [DATASTORE_ID_TEST_BUFFER] =
        /* Test buffer */
            {
                .id = DATASTORE_ID_TEST_BUFFER,
                .name = "TestBuffer",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = { AUTH_ANY, AUTH_ANY },
                .type = DATASTORE_ITEM_TYPE_BUFFER,
                .interface = &datastore_buffer_interface,
                .value_ptr = (void*)&datastore_values.test_buffer,
                .default_value = { .buffer_value = &default_test_buffer, },
                .constraints =
                    {
                        .buffer_constraints =
                            {
                                .min_len = TEST_BUFFER_MIN_LEN,
                                .max_len = TEST_BUFFER_MAX_LEN,
                            },
                    },
            },
        [DATASTORE_ID_SPI_TX_BUFFER] =
        /* SPI TX buffer */
            {
                .id = DATASTORE_ID_SPI_TX_BUFFER,
                .name = "SpiTxBuffer",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = { AUTH_ANY, AUTH_ANY },
                .type = DATASTORE_ITEM_TYPE_STRUCT,
                .interface = &datastore_struct_spi_buffer_interface,
                .value_ptr = (void*)&datastore_values.spi_tx_buffer, /* SpiBuffer_t** */
                .default_value = { .raw_value = &default_spi_tx_buffer, },
                .constraints =
                    {
                        .buffer_constraints = { 0 },
                    },
            },
    };
