/**
 * @file generated_datastore_enums.c
 *
 * @brief Datastore enumeration definitions
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-19
 *
 * @copyright Copyright (c) 2026
 *
 */

#include "generated_datastore_enums.h"

/**
 * @addtogroup datastore
 * @{
 */

const struct data_enum_value BleConnectionState_enum_values[BleConnectionState_COUNT] = {
    {
        .value = 0,
        .name = "DISCONNECTED",
    },
    {
        .value = 1,
        .name = "CONNECTED",
    },
};

const struct data_enum_value Toggle_enum_values[Toggle_COUNT] = {
    {
        .value = 0,
        .name = "DISABLED",
    },
    {
        .value = 1,
        .name = "ENABLED",
    },
};

const struct data_enum_value SpiChipSelect_enum_values[SpiChipSelect_COUNT] = {
    {
        .value = 0,
        .name = "SPI_CS0",
    },
    {
        .value = 1,
        .name = "SPI_CS1",
    },
};

/**
 * @}
 */
