/**
 * @file generated_datastore_items.c
 * @author Demizo (demizodemazo@gmail.com)
 * @brief Datastore item definitions
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @version 0.1
 * @date 2026-03-01
 *
 * @copyright Copyright (c) 2026
 *
 */

#include "generated_datastore_items.h"

#include <limits.h>

#include "buffer.h"
#include "datastore_type_buffer.h"
#include "datastore_type_byte_array.h"
#include "datastore_type_float.h"
#include "datastore_type_int.h"
#include "datastore_type_string.h"
#include "datastore_types.h"

//**********************************************************
//* Local Definitions
//**********************************************************

//**********************************************************
//* Static Function Declarations
//**********************************************************

//**********************************************************
//* Static Variable Definitions
//**********************************************************

static buffer_t default_test_bytes = {
    .len = 6,
    .buf = { 0xDE, 0xAD, 0xBE, 0xEF, 0x00, 0x00, },
};
static buffer_t default_test_buffer = {
    .len = 8,
    .buf = { 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, },
};

struct datastore_values datastore_values = { 0 };

const struct datastore_item_const_metadata
    g_datastore_const_metadata[DATASTORE_ID_COUNT] = {
        [DATASTORE_ID_DATASTORE_HASH] =
            {
                .id = DATASTORE_ID_DATASTORE_HASH,
                .name = "DatastoreHash",
                .storage_type = DATASTORE_STORAGE_CONSTANT,
                .permissions = {0, 0},
                .type = DATASTORE_ITEM_TYPE_STRING,
                .interface = &datastore_string_interface,
                .value_ptr = &datastore_values.datastore_hash,
                .default_value = {.string_value = "TODO",},
                .type_info =
                    {
                        .string_info =
                            {
                                .max_len = 32,
                            },
                    },
            },
        [DATASTORE_ID_DEVICE_NAME] =
            {
                .id = DATASTORE_ID_DEVICE_NAME,
                .name = "DeviceName",
                .storage_type = DATASTORE_STORAGE_PERSISTENT,
                .permissions = {0, 0},
                .type = DATASTORE_ITEM_TYPE_STRING,
                .interface = &datastore_string_interface,
                .value_ptr = &datastore_values.device_name,
                .default_value = {.string_value = "ZDS"},
                .type_info =
                    {
                        .string_info =
                            {
                                .max_len = 32,
                            },
                    },
            },
        [DATASTORE_ID_VERSION_CODE] =
            {
                .id = DATASTORE_ID_VERSION_CODE,
                .name = "VersionCode",
                .storage_type = DATASTORE_STORAGE_PERSISTENT,
                .permissions = {0, 0},
                .type = DATASTORE_ITEM_TYPE_INT,
                .interface = &datastore_int_interface,
                .value_ptr = &datastore_values.version_code,
                .default_value = {.int_value = 1},
                .type_info =
                    {
                        .int_info =
                            {
                                .min = 0,
                                .max = INT_MAX,
                            },
                    },
            },
        [DATASTORE_ID_TEST_FLOAT] =
            {
                .id =DATASTORE_ID_TEST_FLOAT,
                .name = "TestFloat",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = {0, 0},
                .type = DATASTORE_ITEM_TYPE_FLOAT,
                .interface = &datastore_float_interface,
                .value_ptr = &datastore_values.test_float,
                .default_value = {.float_value = 0.5f,},
                .type_info =
                    {
                        .float_info =
                            {
                                .min = 0.0f,
                                .max = 32.0f,
                            },
                    },
            },
        [DATASTORE_ID_TEST_BYTES] =
            {
                .id =DATASTORE_ID_TEST_BYTES,
                .name = "TestBytes",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = {0, 0},
                .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY,
                .interface = &datastore_byte_array_interface,
                .value_ptr = &datastore_values.test_bytes,
                .default_value = {.buffer_value = &default_test_bytes,},
                .type_info =
                    {
                        .byte_array_info =
                            {
                                .size = 6,
                            },
                    },
            },
        [DATASTORE_ID_TEST_BUFFER] =
            {
                .id =DATASTORE_ID_TEST_BUFFER,
                .name = "TestBuffer",
                .storage_type = DATASTORE_STORAGE_EPHEMERAL,
                .permissions = {0, 0},
                .type = DATASTORE_ITEM_TYPE_BYTE_BUFFER,
                .interface = &datastore_buffer_interface,
                .value_ptr = (void*)&datastore_values.test_buffer,
                .default_value = {.buffer_value = &default_test_buffer,},
                .type_info =
                    {
                        .byte_buffer_info =
                            {
                                .min_len = 6,
                                .max_len = 8,
                            },
                    },
            },
};

//**********************************************************
//* Static Function Definitions
//**********************************************************

//**********************************************************
//* Public Function Definitions
//**********************************************************
