/**
 * @file generated_struct_SpiBuffer.c
 *
 * @brief Datastore interface implementation for SpiBuffer struct type
 *
 * @warning !!! DO NOT EDIT !!! Generated by generate_datastore.py
 *
 * @date 2026-04-19
 *
 * @copyright Copyright (c) 2026
 *
 */

#include "generated_struct_SpiBuffer.h"

#include <stdint.h>
#include <string.h>
#include <sys/errno.h>
#include <zephyr/kernel.h>
#include <zephyr/logging/log.h>

#include "buffer.h"
#include "datastore_type_buffer.h"
#include "datastore_type_byte_array.h"
#include "datastore_type_enum.h"
#include "datastore_type_float.h"
#include "datastore_type_int.h"
#include "datastore_type_string.h"
#include "datastore_types.h"
#include "error.h"
#include "generated_datastore_enums.h"
#include "memory.h"
#include "string_utils.h"

/**
 * @brief Logger for module
 */
LOG_MODULE_REGISTER(datastore_struct_spi_buffer, CONFIG_DATASTORE_TYPES_LOG_LEVEL);

//**********************************************************
//* Static Function Declarations
//**********************************************************

static bool validate(const struct datastore_item_const_metadata* item, data_value_t value);
static bool is_default(const struct datastore_item_const_metadata* item);
static void set(const struct datastore_item_const_metadata* item, data_value_t value);
static int get(const struct datastore_item_const_metadata* item, data_value_t* out_value);
static void release(data_value_t* value);
static int encode(zcbor_state_t* encoder, data_value_t value);
static int decode(zcbor_state_t* decoder, data_value_t* out_value);
static int encode_constraints(zcbor_state_t* encoder, const struct datastore_item_const_metadata* item);

//**********************************************************
//* Static Variable Definitions
//**********************************************************

static const struct datastore_item_const_metadata s_spi_buffer_cs_meta = {
    .type = DATASTORE_ITEM_TYPE_ENUM,
    .constraints.enum_constraints = {
        .value_count = 2,
        .values = SpiChipSelect_enum_values,
    },
};

static const struct datastore_item_const_metadata s_spi_buffer_bytes_meta = {
    .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY,
    .constraints.buffer_constraints = {
        .min_len = 0,
        .max_len = 6,
    },
};

static const struct datastore_item_const_metadata s_spi_buffer_text_meta = {
    .type = DATASTORE_ITEM_TYPE_STRING,
    .constraints.buffer_constraints = {
        .min_len = 3,
        .max_len = 12,
    },
};

static const struct datastore_item_const_metadata s_spi_buffer_buffer_meta = {
    .type = DATASTORE_ITEM_TYPE_BUFFER,
    .constraints.buffer_constraints = {
        .min_len = 0,
        .max_len = 512,
    },
};

//**********************************************************
//* Static Function Definitions
//**********************************************************

static bool validate(const struct datastore_item_const_metadata* item, data_value_t value)
{
    ARG_UNUSED(item);
    ASSERT(value.type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");
    SpiBuffer_t* s = (SpiBuffer_t*)value.data.raw_value;

    // Check CS
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_ENUM, .data.int_value = s->cs };
        if (!datastore_enum_interface.validate(&s_spi_buffer_cs_meta, fval)) return false;
    }
    // Check Bytes
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY, .data.buffer_value = s->bytes };
        if (!datastore_byte_array_interface.validate(&s_spi_buffer_bytes_meta, fval)) return false;
    }
    // Check Text
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_STRING, .data.string_value = s->text };
        if (!datastore_string_interface.validate(&s_spi_buffer_text_meta, fval)) return false;
    }
    // Check Buffer
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BUFFER, .data.buffer_value = s->buffer };
        if (!datastore_buffer_interface.validate(&s_spi_buffer_buffer_meta, fval)) return false;
    }

    return true;
}

static bool is_default(const struct datastore_item_const_metadata* item)
{
    SpiBuffer_t* current = *(SpiBuffer_t**)item->value_ptr;
    if (current == NULL) return false;
    SpiBuffer_t* def = (SpiBuffer_t*)item->default_value.raw_value;

    // Check CS
    if (current->cs != def->cs) return false;
    // Check Bytes
    buffer_t* current_bytes = (buffer_t*)(current->bytes);
    buffer_t* default_bytes = (buffer_t*)(def->bytes);
    if (current_bytes->len != default_bytes->len) return false;
    if (memcmp(current_bytes->buf, default_bytes->buf, default_bytes->len) != 0) return false;
    // Check Text
    if (strcmp(current->text, def->text) != 0) return false;
    // Check Buffer
    if (current->buffer->len != def->buffer->len) return false;
    if (memcmp(current->buffer->buf, def->buffer->buf, def->buffer->len) != 0) return false;

    return true;
}

static void release_struct_fields(SpiBuffer_t* s)
{
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_STRING, .data.string_value = s->text };
        datastore_string_interface.release(&fval);
    }
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BUFFER, .data.buffer_value = s->buffer };
        datastore_buffer_interface.release(&fval);
    }
    (void)s;
}

static void set(const struct datastore_item_const_metadata* item, data_value_t value)
{
    ASSERT(value.type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");
    SpiBuffer_t* src = (SpiBuffer_t*)value.data.raw_value;

    // Allocate new struct block
    void* new_block = NULL;
    int ret = mem_alloc(sizeof(SpiBuffer_t), &new_block);
    if (ret != SUCCESS)
    {
        PASS_OWNERSHIP(new_block);
        return;
    }

    SpiBuffer_t* new_struct = (SpiBuffer_t*)new_block;
    memset(new_struct, 0, sizeof(SpiBuffer_t));

    // Copy CS
    new_struct->cs = src->cs;

    // Copy Bytes
    buffer_t* new_bytes = (buffer_t*)(new_struct->bytes);
    buffer_t* src_bytes = (buffer_t*)(src->bytes);
    new_bytes->len = src_bytes->len;
    memcpy(new_bytes->buf, src_bytes->buf, src_bytes->len);

    // Copy Text
    {
        uint16_t str_len =
            (uint16_t)strnlen(src->text, s_spi_buffer_text_meta.constraints.buffer_constraints.max_len) + 1;
        void* new_str_block = NULL;
        ret = mem_alloc(str_len, &new_str_block);
        if (ret != SUCCESS)
        {
            NOT_REFERENCED(new_str_block);
            release_struct_fields(new_struct);
            mem_unref(&new_block);
            return;
        }
        strscpy((char*)new_str_block, src->text, str_len);
        new_struct->text = (char*)new_str_block;
        PASS_OWNERSHIP(new_str_block);
    }

    // Copy Buffer
    {
        void* new_field_block = NULL;
        ret = mem_alloc(sizeof(buffer_t) + src->buffer->len, &new_field_block);
        if (ret != SUCCESS)
        {
            NOT_REFERENCED(new_field_block);
            release_struct_fields(new_struct);
            mem_unref(&new_block);
            return;
        }
        buffer_t* new_field = (buffer_t*)new_field_block;
        new_field->len = src->buffer->len;
        memcpy(new_field->buf, src->buffer->buf, src->buffer->len);
        new_struct->buffer = new_field;
        PASS_OWNERSHIP(new_field_block);
    }

    // Release old value
    SpiBuffer_t* old_struct = *(SpiBuffer_t**)item->value_ptr;
    if (old_struct != NULL)
    {
        data_value_t old_value = { .type = DATASTORE_ITEM_TYPE_STRUCT, .data.raw_value = old_struct };
        release(&old_value);
    }

    *(SpiBuffer_t**)item->value_ptr = (SpiBuffer_t*)new_block;
    PASS_OWNERSHIP(new_block);
}

static int get(const struct datastore_item_const_metadata* item, data_value_t* out_value)
{
    SpiBuffer_t* current = *(SpiBuffer_t**)item->value_ptr;

    mem_ref(current);
    out_value->type = DATASTORE_ITEM_TYPE_STRUCT;
    out_value->data.raw_value = current;

    PASS_OWNERSHIP(current);
    return SUCCESS;
}

static void release(data_value_t* value)
{
    ASSERT(value->type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");

    SpiBuffer_t* s = (SpiBuffer_t*)value->data.raw_value;

    // Free fields if struct is about to be freed
    if (s != NULL && mem_get_ref_count((void*)s) == 1)
    {
        release_struct_fields(s);
    }

    void* ptr = s;
    mem_unref(&ptr);
}

static int encode(zcbor_state_t* encoder, data_value_t value)
{
    ASSERT(value.type == DATASTORE_ITEM_TYPE_STRUCT, "Unexpected value type");
    SpiBuffer_t* s = (SpiBuffer_t*)value.data.raw_value;

    if (!zcbor_list_start_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    // Encode CS
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_ENUM, .data.int_value = s->cs };
        int ret = datastore_enum_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }
    // Encode Bytes
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BYTE_ARRAY, .data.buffer_value = s->bytes };
        int ret = datastore_byte_array_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }
    // Encode Text
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_STRING, .data.string_value = s->text };
        int ret = datastore_string_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }
    // Encode Buffer
    {
        data_value_t fval = { .type = DATASTORE_ITEM_TYPE_BUFFER, .data.buffer_value = s->buffer };
        int ret = datastore_buffer_interface.encode(encoder, fval);
        if (ret != SUCCESS) return ret;
    }

    if (!zcbor_list_end_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    return SUCCESS;
}

static int decode(zcbor_state_t* decoder, data_value_t* out_value)
{
    if (!zcbor_list_start_decode(decoder))
    {
        return -EBADMSG;
    }

    void* new_block = NULL;
    int ret = mem_alloc(sizeof(SpiBuffer_t), &new_block);
    if (ret != SUCCESS)
    {
        NOT_REFERENCED(new_block);
        return ret;
    }

    SpiBuffer_t* new_struct = (SpiBuffer_t*)new_block;
    memset(new_struct, 0, sizeof(SpiBuffer_t));

    // Decode CS
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_ENUM;
        ret = datastore_enum_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        new_struct->cs = fval.data.int_value;
        datastore_enum_interface.release(&fval);
    }
    // Decode Bytes
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_BYTE_ARRAY;
        ret = datastore_byte_array_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        // Validate now to avoid copying an invalid buffer
        if (!datastore_byte_array_interface.validate(&s_spi_buffer_bytes_meta, fval))
        {
            datastore_byte_array_interface.release(&fval);
            goto decode_cleanup;
        }
        buffer_t* new_bytes = (buffer_t*)(new_struct->bytes);
        buffer_t* decoded_bytes = fval.data.buffer_value;
        new_bytes->len = decoded_bytes->len;
        memcpy(new_bytes->buf, decoded_bytes->buf, decoded_bytes->len);
        datastore_byte_array_interface.release(&fval);
    }
    // Decode Text
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_STRING;
        ret = datastore_string_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        void* decoded_field_ptr = fval.data.string_value;
        new_struct->text = decoded_field_ptr;
        PASS_OWNERSHIP(decoded_field_ptr);
    }
    // Decode Buffer
    {
        data_value_t fval = { 0 };
        fval.type = DATASTORE_ITEM_TYPE_BUFFER;
        ret = datastore_buffer_interface.decode(decoder, &fval);
        if (ret != SUCCESS) goto decode_cleanup;
        void* decoded_field_ptr = fval.data.buffer_value;
        new_struct->buffer = decoded_field_ptr;
        PASS_OWNERSHIP(decoded_field_ptr);
    }

    if (!zcbor_list_end_decode(decoder))
    {
        ret = -EBADMSG;
        goto decode_cleanup;
    }

    out_value->type = DATASTORE_ITEM_TYPE_STRUCT;
    out_value->data.raw_value = new_block;
    PASS_OWNERSHIP(new_block);
    return SUCCESS;

decode_cleanup:
    release_struct_fields(new_struct);
    mem_unref(&new_block);
    return ret;
}

static int encode_constraints(zcbor_state_t* encoder, const struct datastore_item_const_metadata* item)
{
    (void)item;

    if (!zcbor_list_start_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    {
        struct zcbor_string name_str = { .value = "CS", .len = 2 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_ENUM))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_enum_interface.encode_constraints(encoder, &s_spi_buffer_cs_meta);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }
    {
        struct zcbor_string name_str = { .value = "Bytes", .len = 5 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_BYTE_ARRAY))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_byte_array_interface.encode_constraints(encoder, &s_spi_buffer_bytes_meta);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }
    {
        struct zcbor_string name_str = { .value = "Text", .len = 4 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_STRING))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_string_interface.encode_constraints(encoder, &s_spi_buffer_text_meta);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }
    {
        struct zcbor_string name_str = { .value = "Buffer", .len = 6 };
        if (!zcbor_map_start_encode(encoder, 3) || !zcbor_tstr_put_lit(encoder, "name") ||
            !zcbor_tstr_encode(encoder, &name_str) || !zcbor_tstr_put_lit(encoder, "type") ||
            !zcbor_uint32_put(encoder, (uint32_t)DATASTORE_ITEM_TYPE_BUFFER))
        {
            return -ENOMEM;
        }
        if (!zcbor_tstr_put_lit(encoder, "constraints"))
        {
            return -ENOMEM;
        }
        {
            int ret = datastore_buffer_interface.encode_constraints(encoder, &s_spi_buffer_buffer_meta);
            if (ret != SUCCESS) return ret;
        }
        if (!zcbor_map_end_encode(encoder, 3))
        {
            return -ENOMEM;
        }
    }

    if (!zcbor_list_end_encode(encoder, 4))
    {
        return -ENOMEM;
    }

    return SUCCESS;
}

//**********************************************************
//* Public Function Definitions
//**********************************************************

const struct datastore_item_interface datastore_struct_spi_buffer_interface = {
    .validate = validate,
    .is_default = is_default,
    .set = set,
    .get = get,
    .release = release,
    .decode = decode,
    .encode = encode,
    .encode_constraints = encode_constraints,
};
